### PR TITLE
Added a line to README, create new file

### PR DESCRIPTION
**Pull request by luekharrison**
Testing to create instructions

### CODE REVIEW

**Comment by mjdavies** [comment]
Did you create a new file and try to get that into the repo as well Luke?  You have to use git add to add specific files that aren't already in the repo, then git commit the addition, then push up.

Do you want to try now?

**Comment by luekharrison** [comment]
Just gave it a shot

**Comment by mjdavies** [comment]
Looks good Luke, I'm going to approve the review, then it's up to you to merge it in.  We may have a permissions issue at that point, not sure, let me know.

**Review by mjdavies — APPROVED** [review]
Good comms through the github interface Luke, and also resolved adding a file without too much pain :-)

**Pull request merged**
